### ISSUE TITLE
Возможность получать вложенные значения через model.previous()

### ISSUE THREAD

**Issue by soulhunter1987** [ZaValera/backbone.ribs#35]
Было бы удобно в метод model.previous() добавить так же возможность получать значения вложенных свойств (по аналогии с model.get()), например:
model.previous('outer.inner');

**Comment by dmitriy-chertkov** [comment]
Создавал pull request #30 с реализацией `model.previous('outer.inner')`, но автор отклонил.

**Comment by soulhunter1987** [comment]
Интересно, почему?

**Comment by dmitriy-chertkov** [comment]
Т.к. при каждом set нужно выполнять "глубокое" клонирование, это дорогая операция.
Может сделать опцию для включения этой фичи?

**Comment by soulhunter1987** [comment]
Ну да, вполне логично сделать опцию а-ля savePrevious или что-то такое, думаю будет востребовано в определенных случаях...

**Comment by ZaValera** [comment]
Я добавил такую возможность, но пользуйтесь ею на свой страх и риск.
`Backbone.Ribs.Model.extend({deepPrevious: true})`

**Comment by dmitriy-chertkov** [comment]
В underscore нет метода `cloneDeep`, но в моем проекте это будет работать т.к. underscore это алиас на lodash

**Comment by ZaValera** [comment]
>В underscore нет метода `cloneDeep`
underscore продолжает удивлять. Я тоже давно пользуюсь lodash, поэтому даже предположить такого не мог.
Спасибо, что заметили, придется добавлять.
