### ISSUE TITLE
Ошибка установки свойства модели 

### ISSUE THREAD

**Issue by SchDen** [ZaValera/backbone.ribs#44]
При использовании вложенного присвоения атрибутов модели натолкнулся на досадную ошибку.
Суть в том, что при выполнении метода set. внутри обработчика изменения атрибута модели, вываливается ошибка (конкретный пример далее): 
```javascript
"Uncaught Error: can't get "status" of "id963", "id963" is undefined"
```
Т.е - я слушаю событие изменения модели и при вызове обработчика не могу изменить значение этой же модели.

[Сделал общий пример с ошибкой: ](http://pastebin.com/7R3KNjFa)

Ковырялся долго, но по итогу нашел только как можно сделать, через `setTimeout`
[Пример рабочего кода](http://pastebin.com/LGFM6tzk)

Хотелось бы разобраться с причиной ошибки)

version: '0.5.1'

**Comment by ZaValera** [comment]
Спасибо за интересный баг и качественный отчет.
Исправил в версии 0.5.2

**Comment by SchDen** [comment]
Пожалуйста :) А можно чуть чуть пояснить причину возникновения бага? Из коммита не очень воспринял

**Comment by ZaValera** [comment]
Ну тут без 100 грамм сложно))
Источник бага в том, что в Ribs нельзя делать вот так:
```javascript
var Model = Backbone.Ribs.Model.extend({
    defaults: {
        first: 123
    }
});

var model = new Model();

model.get('first.second.third');
```
Т.е. нельзя прочитать свойство у несуществующего объекта.
Вы получите ровно то исключение, которое видели в своем примере.
Можно было бы конечно возвращать undefined, но я исходил из того, что в JS:
```javascript
var first = {};

console.log(first.second.third);
```
подобный код тоже с генерирует исключение.

А теперь к багу. Когда вы set-ите в модель, backbone сохраняет previous атрибуты и сравнивает новое значение с предыдущим, чтобы понять, изменилось ли оно. Но он делает это один раз в начале самого set-a. Если в обработчике изменения модели происходит set в эту же модель, то backbone работает с теми previous которые были сохранены на момент первого set-а.
Как раз ваш случай. И получается, что была попытка найти поле
```javascript
id963.status
```
в объекте
```javascript
{
    id967: {
        status: null
    }
}
```
что и приводило к ошибке.

Не знаю, можно ли из моего объяснения что-то понять, но я старался)

**Comment by SchDen** [comment]
Спасибо, вроде бы все понятно))
